import Head from 'next/head';
import Hero from '../components/Hero';
import About from '../components/About';
import Layout from '../components/Layout';
import Services from '../components/Services';
import Portofolio from '../components/Portofolio';
import Contact from '../components/Contact';
import Products from '../components/Products';


export default function Home() {
  return (
    <div>
      <Layout>
        <Head>
          <title>IDM | Official</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <Hero />
        <About />
        <Services />
        <Portofolio />
        <Products />
        <Contact />
      </Layout>
    </div>
  );
}
